name: offline_market_data
description: Simple and easy to use price data for any purposes.
version: 0.0.0
repository: https://git.mrcyjanek.net/mrcyjanek/offline_market_data
publish_to: https://git.mrcyjanek.net/api/packages/mrcyjanek/pub
environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  http: any
  sprintf: any
